version: '3.1'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_DB=willhastings_me
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: . # Use Dockerfile in this directory.
    command: bin/start-docker
    volumes:
      - .:/app # Use current directory as /app directory in container.
      - /app/node_modules # Keep node_modules out of the image.
      - /app/dist # Keep built app out of the image.
      - yarn-cache:/root/.cache/yarn
      - node-modules:/app/node_modules
      - app-build:/app/dist
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgres://app@db:5432/willhastings_me
    links:
      - db
  box:
    image: busybox
    volumes:
      - yarn-cache:/root/.cache/yarn
      - node-modules:/app/node_modules
      - app-build:/app/dist
      - pgdata:/pgdata
volumes:
  yarn-cache:
  node-modules:
  app-build:
  pgdata:
